on:
  workflow_dispatch:

jobs:
  retrieve-secret:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Retrieve secret from Vault
        uses: hashicorp/vault-action@v2
        with:
          url: https://plaza-unusable-quickstep.ngrok-free.dev
          method: jwt
          role: github-role
          jwtGithubAudience: my-audience
          secrets: |
            secret/data/ci/aws accessKey | AWS_ACCESS_KEY_ID ;

      - name: Use secret from Vault
        run: |
          # This step has access to the secret retrieved above; see hashicorp/vault-action for more details.
          echo "hello world"
